import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header/header";
import Footer from "@/components/footer";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";
import { RetreatProvider } from "@/context/retreat";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "JV Ventures",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider enableSystem={true} attribute="class">
        <RetreatProvider>
          <body>
            <Header />
            <Toaster />
            {children}
            <Footer />
          </body>
        </RetreatProvider>
      </ThemeProvider>
    </html>
  );
}
